name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set R Library home on Linux
        if: runner.os == 'Linux'
        run: |
          mkdir -p ~/R_library
          echo ".libPaths('~/R_library')" > ~/.Rprofile

      - uses: r-lib/actions/setup-r@v1

      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          Rscript -e 'install.packages("remotes")'
          sysreqs=$(Rscript -e 'cat("apt-get update -y && apt-get install -y", paste(gsub("apt-get install -y ", "", remotes::system_requirements("ubuntu", "20.04", path = "tests/scripts/")), collapse = " "))')
          echo $sysreqs
          sudo -s eval "$sysreqs"

      - name: Install R dependencies
        shell: Rscript {0}
        run: |
          remotes::install_deps(pkgdir = "tests/scripts/", dependencies = TRUE)
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build package
        run: |
          poetry install
          poetry build

      - name: Lint package
        run: poetry run black --check --diff .

      - name: Lint R test scripts
        shell: Rscript {0}
        run: |
          lintr::lint_dir("tests/")
          quit(save = "no", status = length(lintr::lint_dir("tests/")))

      - name: Test package
        run: poetry run pytest -v tests/
  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: test

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Build package
        run: |
          poetry install
          poetry build

      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
